//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity_Log
    {
        public int log_id { get; set; }
        public string username { get; set; }
        public Nullable<System.DateTime> datetime_performed { get; set; }
        public Nullable<int> action_level { get; set; }
        public string action { get; set; }
        public string description { get; set; }
        public string department { get; set; }
        public string division { get; set; }
    }
}
