//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChecklistTable
    {
        public int checkListId { get; set; }
        public Nullable<int> parentWeeklyReference { get; set; }
        public Nullable<int> parentSubReference { get; set; }
        public string title { get; set; }
        public string duration { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> targetDate { get; set; }
    }
}
