//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChecklistSubmission
    {
        public int submission_id { get; set; }
        public string submission_description { get; set; }
        public string task_name { get; set; }
        public Nullable<int> task_id { get; set; }
        public string submitted_by { get; set; }
        public Nullable<System.DateTime> submission_date { get; set; }
        public Nullable<bool> is_approved { get; set; }
        public string filepath { get; set; }
        public Nullable<int> main_id { get; set; }
        public Nullable<int> milestone_id { get; set; }
        public string approved_by { get; set; }
        public Nullable<System.DateTime> approval_date { get; set; }
        public string disapproval_reason { get; set; }
        public Nullable<bool> is_removed { get; set; }
        public Nullable<bool> approval_enabled { get; set; }
        public string type { get; set; }
    }
}
