

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProjectManagementSystem.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class ProjectManagementDBEntities : DbContext
{
    public ProjectManagementDBEntities()
        : base("name=ProjectManagementDBEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<ChecklistTable> ChecklistTables { get; set; }

    public virtual DbSet<Report> Reports { get; set; }

    public virtual DbSet<WeeklyChecklistTable> WeeklyChecklistTables { get; set; }

}

}

