
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProjectManagementSystem.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ChecklistTable
{

    public int id { get; set; }

    public string text { get; set; }

    public int duration { get; set; }

    public string start_date { get; set; }

    public Nullable<int> parent { get; set; }

    public Nullable<int> weeklyReference { get; set; }

    public Nullable<int> source { get; set; }

    public Nullable<int> target { get; set; }

    public string type { get; set; }

    public Nullable<int> ofYear { get; set; }

    public Nullable<int> inWeek { get; set; }

    public string title { get; set; }

}

}
