//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChecklistSetup
    {
        public int cl_sett_id { get; set; }
        public string checklist_name { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<System.DateTime> date_removed { get; set; }
        public Nullable<bool> is_active { get; set; }
        public string created_by { get; set; }
        public string division { get; set; }
        public Nullable<int> milestone_id { get; set; }
        public Nullable<bool> project_specific { get; set; }
        public Nullable<int> main_id { get; set; }
    }
}
