
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProjectManagementSystem.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ChecklistTable
{

    public int id { get; set; }

    public Nullable<int> sequenceId { get; set; }

    public string text { get; set; }

    public int duration { get; set; }

    public Nullable<System.DateTime> start_date { get; set; }

    public Nullable<System.DateTime> end_date { get; set; }

    public Nullable<int> parent { get; set; }

    public Nullable<int> projectReference { get; set; }

    public Nullable<int> source { get; set; }

    public Nullable<int> target { get; set; }

    public string type { get; set; }

    public Nullable<int> ofYear { get; set; }

    public Nullable<int> startWeek { get; set; }

    public Nullable<int> endWeek { get; set; }

    public string title { get; set; }

    public string projectType { get; set; }

    public string status { get; set; }

    public string color { get; set; }

    public string details { get; set; }

    public Nullable<System.DateTime> dateInitial { get; set; }

    public Nullable<System.DateTime> dateFinished { get; set; }

    public string project_owner { get; set; }

    public string project_name { get; set; }

    public string process { get; set; }

    public Nullable<bool> isUnscheduled { get; set; }

    public Nullable<int> projectId { get; set; }

}

}
