//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChecklistReference
    {
        public int ID { get; set; }
        public Nullable<int> DivisionID { get; set; }
        public string ReferenceNumber { get; set; }
        public Nullable<bool> IsFinalized { get; set; }
        public Nullable<System.DateTime> DateFinalized { get; set; }
        public string FinalizedBy { get; set; }
    }
}
