//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM_WifiAccess
    {
        public int id { get; set; }
        public string CMId { get; set; }
        public string Password { get; set; }
        public string Encoded_by { get; set; }
        public string Edited_by { get; set; }
        public Nullable<bool> Removed_Status { get; set; }
        public string Removed_by { get; set; }
        public string cm_ID { get; set; }
        public string VisitorID { get; set; }
    }
}
