//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailsTbl
    {
        public int details_id { get; set; }
        public Nullable<int> milestone_id { get; set; }
        public Nullable<int> main_id { get; set; }
        public string process_title { get; set; }
        public Nullable<bool> IsSubtask { get; set; }
        public Nullable<System.DateTime> task_start { get; set; }
        public Nullable<System.DateTime> task_end { get; set; }
        public Nullable<int> task_duration { get; set; }
        public Nullable<int> source { get; set; }
        public Nullable<int> target { get; set; }
        public Nullable<int> parent { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string task_status { get; set; }
        public string color_status { get; set; }
        public Nullable<bool> isUnscheduled { get; set; }
        public Nullable<bool> isCompleted { get; set; }
        public string key_person { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> RequiresApproval { get; set; }
    }
}
