//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FixedChecklistTbl
    {
        public int Fixed_Checklist_ID { get; set; }
        public Nullable<int> Checklist_ID { get; set; }
        public Nullable<int> Milestone_ID { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<bool> Project_Specific { get; set; }
        public Nullable<int> Main_ID { get; set; }
    
        public virtual ChecklistSetup ChecklistSetup { get; set; }
        public virtual MilestoneTbl MilestoneTbl { get; set; }
    }
}
