//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MainTable()
        {
            this.MilestoneTbls = new HashSet<MilestoneTbl>();
        }
    
        public int main_id { get; set; }
        public string project_title { get; set; }
        public Nullable<System.DateTime> project_start { get; set; }
        public Nullable<System.DateTime> project_end { get; set; }
        public Nullable<int> duration { get; set; }
        public Nullable<int> year { get; set; }
        public string division { get; set; }
        public string category { get; set; }
        public string project_owner { get; set; }
        public string user_id { get; set; }
        public Nullable<bool> isCompleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MilestoneTbl> MilestoneTbls { get; set; }
    }
}
