//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MilestoneTbl
    {
        public int milestone_id { get; set; }
        public Nullable<int> main_id { get; set; }
        public string milestone_name { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<int> milestone_position { get; set; }
        public string status_update { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public Nullable<bool> unscheduled { get; set; }
        public Nullable<int> parent { get; set; }
        public Nullable<int> excel_id { get; set; }
        public Nullable<int> source { get; set; }
        public Nullable<int> target { get; set; }
    
        public virtual MainTable MainTable { get; set; }
    }
}
