//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MilestoneTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MilestoneTbl()
        {
            this.DetailsTbls = new HashSet<DetailsTbl>();
        }
    
        public int milestone_id { get; set; }
        public Nullable<int> main_id { get; set; }
        public string milestone_name { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<int> milestone_position { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailsTbl> DetailsTbls { get; set; }
        public virtual MainTable MainTable { get; set; }
    }
}
