//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int notification_id { get; set; }
        public string cmid_user { get; set; }
        public string message { get; set; }
        public string link { get; set; }
        public string type { get; set; }
        public bool is_read { get; set; }
        public int main_id { get; set; }
        public int milestone_id { get; set; }
        public int task_id { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
    }
}
