//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptionalMilestone
    {
        public int id { get; set; }
        public Nullable<int> main_id { get; set; }
        public Nullable<int> milestone_id { get; set; }
        public string division { get; set; }
        public string task { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public string created_by { get; set; }
        public Nullable<bool> is_removed { get; set; }
        public string removed_by { get; set; }
        public Nullable<System.DateTime> date_removed { get; set; }
        public Nullable<bool> approved { get; set; }
    }
}
