//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptionalMilestoneApprover
    {
        public int id { get; set; }
        public string approver_name { get; set; }
        public string approver_email { get; set; }
        public Nullable<int> main_id { get; set; }
        public Nullable<int> milestone_id { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public string added_by { get; set; }
        public string division { get; set; }
        public Nullable<bool> approved { get; set; }
        public Nullable<bool> rejected { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> date_approved { get; set; }
        public Nullable<bool> is_removed { get; set; }
        public Nullable<System.DateTime> date_removed { get; set; }
        public string removed_by { get; set; }
        public Nullable<int> employee_id { get; set; }
        public Nullable<int> task_id { get; set; }
        public string approver_status { get; set; }
        public string withdraw_reason { get; set; }
        public Nullable<System.DateTime> datetime_withdraw { get; set; }
    }
}
