//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreSetMilestone
    {
        public int ID { get; set; }
        public Nullable<int> DivisionID { get; set; }
        public Nullable<int> MilestoneID { get; set; }
        public string MilestoneName { get; set; }
        public Nullable<int> Sorting { get; set; }
        public string Requirements { get; set; }
        public string Approvers { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Draft { get; set; }
    
        public virtual Division Division { get; set; }
    }
}
