//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectMembersTbl
    {
        public int member_id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public Nullable<int> project_id { get; set; }
        public string division { get; set; }
        public string department { get; set; }
        public Nullable<int> role { get; set; }
        public Nullable<bool> acknowledged { get; set; }
        public Nullable<bool> is_removed { get; set; }
    }
}
