
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProjectManagementSystem.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Report
{

    public int id { get; set; }

    public string division { get; set; }

    public Nullable<int> year { get; set; }

    public Nullable<int> inQuarter { get; set; }

    public string projectName { get; set; }

    public Nullable<double> targetKPI { get; set; }

    public Nullable<double> actualKPI { get; set; }

    public Nullable<double> completionRate { get; set; }

    public string status { get; set; }

    public string currentTask { get; set; }

    public string nextTask { get; set; }

    public string comments { get; set; }

    public string milestoneActual { get; set; }

    public string milestoneTarget { get; set; }

}

}
