//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SavedDivision
    {
        public int SavedDivID { get; set; }
        public Nullable<int> DivisionID { get; set; }
        public string DivisionName { get; set; }
        public Nullable<int> NoOfMilestones { get; set; }
        public Nullable<int> NoOfRequirements { get; set; }
        public Nullable<bool> IsActive_ { get; set; }
    
        public virtual Division Division { get; set; }
    }
}
