//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskApproval
    {
        public int Approval_ID { get; set; }
        public Nullable<int> Details_ID { get; set; }
        public Nullable<int> Approver_ID { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
    
        public virtual DetailsTbl DetailsTbl { get; set; }
    }
}
