//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionTbl
    {
        public int transaction_id { get; set; }
        public Nullable<int> project_id { get; set; }
        public Nullable<bool> registration_check { get; set; }
        public Nullable<bool> teammate_check { get; set; }
        public Nullable<bool> upload_check { get; set; }
        public Nullable<bool> is_complete { get; set; }
        public Nullable<System.DateTime> transaction_date { get; set; }
        public string transaction_user { get; set; }
    }
}
