//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CMInfo
    {
        public string Id { get; set; }
        public string CMId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Division { get; set; }
        public string Department { get; set; }
        public string PositionDescription { get; set; }
        public string Type { get; set; }
        public Nullable<bool> CM_status { get; set; }
        public string Email { get; set; }
        public string PasswordHash { get; set; }
        public int EmpType { get; set; }
        public Nullable<int> JobLevel { get; set; }
    }
}
