//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeeklyChecklistTable
    {
        public int weeklyID { get; set; }
        public string weeklyTitle { get; set; }
        public string weeklyDuration { get; set; }
        public System.DateTime weeklyStart { get; set; }
        public System.DateTime weeklyTarget { get; set; }
        public Nullable<int> weeklyInYear { get; set; }
        public Nullable<int> subMain { get; set; }
        public Nullable<int> subSub { get; set; }
        public string division { get; set; }
        public string category { get; set; }
        public bool week52 { get; set; }
        public bool week51 { get; set; }
        public bool week50 { get; set; }
        public bool week49 { get; set; }
        public bool week48 { get; set; }
        public bool week47 { get; set; }
        public bool week46 { get; set; }
        public bool week45 { get; set; }
        public bool week44 { get; set; }
        public bool week43 { get; set; }
        public bool week42 { get; set; }
        public bool week41 { get; set; }
        public bool week40 { get; set; }
        public bool week39 { get; set; }
        public bool week38 { get; set; }
        public bool week37 { get; set; }
        public bool week36 { get; set; }
        public bool week35 { get; set; }
        public bool week34 { get; set; }
        public bool week33 { get; set; }
        public bool week32 { get; set; }
        public bool week31 { get; set; }
        public bool week30 { get; set; }
        public bool week29 { get; set; }
        public bool week28 { get; set; }
        public bool week27 { get; set; }
        public bool week26 { get; set; }
        public bool week25 { get; set; }
        public bool week24 { get; set; }
        public bool week23 { get; set; }
        public bool week22 { get; set; }
        public bool week21 { get; set; }
        public bool week20 { get; set; }
        public bool week19 { get; set; }
        public bool week18 { get; set; }
        public bool week17 { get; set; }
        public bool week16 { get; set; }
        public bool week15 { get; set; }
        public bool week14 { get; set; }
        public bool week13 { get; set; }
        public bool week12 { get; set; }
        public bool week11 { get; set; }
        public bool week10 { get; set; }
        public bool week9 { get; set; }
        public bool week8 { get; set; }
        public bool week7 { get; set; }
        public bool week6 { get; set; }
        public bool week5 { get; set; }
        public bool week4 { get; set; }
        public bool week3 { get; set; }
        public bool week2 { get; set; }
        public bool week1 { get; set; }
        public Nullable<int> inWeek { get; set; }
        public Nullable<bool> isCancelled { get; set; }
        public Nullable<bool> isDelayed { get; set; }
    }
}
