//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeeklyStatu
    {
        public int status_id { get; set; }
        public Nullable<int> milestone_id { get; set; }
        public string project_owner { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> date_updated { get; set; }
        public string attachment { get; set; }
        public Nullable<int> main_id { get; set; }
        public string user_id { get; set; }
        public string milestone_name { get; set; }
        public Nullable<int> delay { get; set; }
    }
}
