
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProjectManagementSystem.Models
{

using System;
    using System.Collections.Generic;
    
public partial class WeeklyChecklistTable
{

    public int weeklyID { get; set; }

    public string sequenceId { get; set; }

    public string weeklyTitle { get; set; }

    public string weeklyDuration { get; set; }

    public System.DateTime weeklyStart { get; set; }

    public System.DateTime weeklyTarget { get; set; }

    public Nullable<int> weeklyInYear { get; set; }

    public Nullable<int> subMain { get; set; }

    public Nullable<int> subSub { get; set; }

    public string division { get; set; }

    public string category { get; set; }

    public Nullable<int> inWeek { get; set; }

    public Nullable<bool> isCancelled { get; set; }

    public Nullable<bool> isDelayed { get; set; }

    public Nullable<int> WeeklyMonth { get; set; }

    public Nullable<int> WeeklyDay { get; set; }

    public Nullable<bool> isCompleted { get; set; }

    public Nullable<bool> week1 { get; set; }

    public Nullable<bool> week2 { get; set; }

    public Nullable<bool> week3 { get; set; }

    public Nullable<bool> week4 { get; set; }

    public Nullable<bool> week5 { get; set; }

    public Nullable<bool> week6 { get; set; }

    public Nullable<bool> week7 { get; set; }

    public Nullable<bool> week8 { get; set; }

    public Nullable<bool> week9 { get; set; }

    public Nullable<bool> week10 { get; set; }

    public Nullable<bool> week11 { get; set; }

    public Nullable<bool> week12 { get; set; }

    public Nullable<bool> week13 { get; set; }

    public Nullable<bool> week14 { get; set; }

    public Nullable<bool> week15 { get; set; }

    public Nullable<bool> week16 { get; set; }

    public Nullable<bool> week17 { get; set; }

    public Nullable<bool> week18 { get; set; }

    public Nullable<bool> week19 { get; set; }

    public Nullable<bool> week20 { get; set; }

    public Nullable<bool> week21 { get; set; }

    public Nullable<bool> week22 { get; set; }

    public Nullable<bool> week23 { get; set; }

    public Nullable<bool> week24 { get; set; }

    public Nullable<bool> week25 { get; set; }

    public Nullable<bool> week26 { get; set; }

    public Nullable<bool> week27 { get; set; }

    public Nullable<bool> week28 { get; set; }

    public Nullable<bool> week29 { get; set; }

    public Nullable<bool> week30 { get; set; }

    public Nullable<bool> week31 { get; set; }

    public Nullable<bool> week32 { get; set; }

    public Nullable<bool> week33 { get; set; }

    public Nullable<bool> week34 { get; set; }

    public Nullable<bool> week35 { get; set; }

    public Nullable<bool> week36 { get; set; }

    public Nullable<bool> week37 { get; set; }

    public Nullable<bool> week38 { get; set; }

    public Nullable<bool> week39 { get; set; }

    public Nullable<bool> week40 { get; set; }

    public Nullable<bool> week41 { get; set; }

    public Nullable<bool> week42 { get; set; }

    public Nullable<bool> week43 { get; set; }

    public Nullable<bool> week44 { get; set; }

    public Nullable<bool> week45 { get; set; }

    public Nullable<bool> week46 { get; set; }

    public Nullable<bool> week47 { get; set; }

    public Nullable<bool> week48 { get; set; }

    public Nullable<bool> week49 { get; set; }

    public Nullable<bool> week50 { get; set; }

    public Nullable<bool> week51 { get; set; }

    public Nullable<bool> week52 { get; set; }

    public string weeklyOwner { get; set; }

}

}
