
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProjectManagementSystem.Models
{

using System;
    using System.Collections.Generic;
    
public partial class WeeklyStatu
{

    public int status_id { get; set; }

    public string description { get; set; }

    public Nullable<bool> attachment { get; set; }

}

}
